version: '3.8'

services:

  db:
    image: postgres:latest
    container_name: best_travel_db
    restart: always
    volumes:
      - ./db/sql/create_schema.sql:/docker-entrypoint-initdb.d/create_schema.sql
      - ./db/sql/data.sql:/docker-entrypoint-initdb.d/data.sql
    environment:
      - POSTGRES_DB=best_travel
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "54320:5432"

  cache:
    image: redis:latest
    container_name: best_travel_cache
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --loglevel warning --requirepass ${POSTGRES_PASSWORD}